<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Whois.Console</AssemblyName>
    <RootNamespace>Whois</RootNamespace>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>dotnet-whois</ToolCommandName>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>0.0.1-alpha1</Version>
    <PackageId>dotnet-whois</PackageId>
    <Authors>Chris Wood</Authors>
    <Company>flipbit.co.uk</Company>
    <Product>.NET WHOIS Lookup</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.RollingFile" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Whois\Whois.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\Program Files\dotnet\sdk\NuGetFallbackFolder\newtonsoft.json\9.0.1\lib\netstandard1.0\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
