<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Core library -->
<PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.102" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />

    <!-- Console app -->
    <PackageVersion Include="CommandLineParser" Version="2.9.1" />
    <PackageVersion Include="Spectre.Console" Version="0.50.0" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.50.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.10" />

    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.10" />

    <!-- Core library extras -->
    <PackageVersion Include="System.Text.Json" Version="9.0.7" />
    <PackageVersion Include="PolySharp" Version="1.16.0" />
    <PackageVersion Include="Tokenizer" Version="3.0.0" />

    <!-- Analyzers -->
    <PackageVersion Include="Meziantou.Analyzer" Version="3.0.137" />

    <!-- Test -->
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.10" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="NSubstitute" Version="6.0.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
  </ItemGroup>
</Project>
