namespace Whois
{
    public enum WhoisStatus
    {
        Unknown,
        Found, 
        NotFound, 
        Error, 
        Throttled,
        Expired,
        PendingDelete,
        Reserved,
        Suspended,
        NotAssigned,
        Invalid,
        Inactive,
        Locked,
        Quarantined,
        OutOfService,
        NotAvailable,
        Deactivated,
        Failed,
        Unconfirmed,
        Unavailable,
        ToBeReleased,
        Redemption,
        Blocked,
        Other
    }
}
