<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
   <TargetFrameworks>netstandard2.0;net8.0;net10.0</TargetFrameworks>
   <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
   <Version>4.0.0-beta.1</Version>
   <PackageVersion>4.0.0-beta.1</PackageVersion>
   <Authors>Chris Wood</Authors>
   <Company>flipbit.co.uk</Company>
   <PackageProjectUrl>http://github.com/flipbit/whois</PackageProjectUrl>
   <PackageTags>whois lookup parsing</PackageTags>
   <Description>A .NET Standard 2.0, .NET 8, and .NET 10 WHOIS Lookup and Parsing Library</Description>
   <PackageReadmeFile>README.md</PackageReadmeFile>
   <PackageIcon>icon.png</PackageIcon>
   <Copyright>Chris Wood 2021</Copyright>
   <RootNamespace>Whois</RootNamespace>

  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*.txt" />
    <EmbeddedResource Include="Resources\**\*.json" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Whois.Tests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Whois.Refresh</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Whois.Refresh.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="PolySharp" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Tokenizer" />
  </ItemGroup>

  <PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
